// Core audit data model for SiteDoc AI.
//
// This model is intentionally forward-looking: it already describes the full
// set of audit categories and per-category scores that the product targets
// (accessibility, SEO, performance, UX, best practices), even though earlier
// phases only populate a subset. New fields are optional so the scanner and UI
// can adopt them incrementally without breaking changes.

export type AuditStatus = "queued" | "running" | "completed" | "failed";

/**
 * Deterministic analyzers that can run during a scan. Used both to drive the
 * audit-module toggles in the UI and to tag where each issue came from.
 */
export type AuditModule =
  | "accessibility"
  | "seo"
  | "performance"
  | "console"
  | "network"
  | "screenshots";

export type AuditModuleSelection = Record<AuditModule, boolean>;

export const DEFAULT_MODULE_SELECTION: AuditModuleSelection = {
  accessibility: true,
  seo: true,
  performance: true,
  console: true,
  network: true,
  screenshots: true,
};

/**
 * High-level category an issue belongs to. `Scanner` is a catch-all for
 * scan-runtime problems; `Console`/`Network` are kept as distinct buckets
 * because they map directly to browser signals.
 */
export type AuditCategory =
  | "Accessibility"
  | "SEO"
  | "Performance"
  | "UX"
  | "BestPractices"
  | "Scanner"
  | "Console"
  | "Network";

export type AuditSeverity = "High" | "Medium" | "Low";

export type AuditIssue = {
  id: string;
  category: AuditCategory;
  severity: AuditSeverity;
  title: string;
  /** CSS selector or locator for the offending element, when applicable. */
  selector?: string;
  detail: string;
  fix: string;
  /** Documentation link explaining the rule (e.g. axe-core help URL). */
  helpUrl?: string;
  /** Human-readable impact tag from the analyzer (e.g. axe "serious"). */
  impact?: string;
  /** Relative weight used by scoring; higher means a bigger score penalty. */
  weight?: number;
  /** Optional copy-pasteable fix snippet generated by deterministic checks or AI. */
  codeSnippet?: string;
};

export type ConsoleError = {
  text: string;
  type: string;
  url?: string;
  lineNumber?: number;
  columnNumber?: number;
};

export type FailedRequest = {
  url: string;
  method: string;
  resourceType: string;
  failureText: string;
  status?: number;
};

export type AuditMetric = {
  label: string;
  value: string;
  detail: string;
};

export type AuditScreenshots = {
  desktop?: string;
  mobile?: string;
};

/**
 * Per-category and overall scores (0-100). `overall` is always present once a
 * scan completes; category scores are present only for categories that ran.
 * `scanner`/`console`/`network` are retained as legacy sub-signals that feed
 * into the broader categories and remain populated by the current scanner.
 */
export type AuditScores = {
  overall: number;
  accessibility?: number;
  seo?: number;
  performance?: number;
  ux?: number;
  bestPractices?: number;
  // Legacy sub-signals (still emitted by the current scanner).
  scanner: number;
  console: number;
  network: number;
};

export type AuditRecord = {
  id: string;
  url: string;
  finalUrl?: string;
  status: AuditStatus;
  /** Locale the audit content was generated in (BCP-47 short code). */
  language?: string;
  createdAt: string;
  completedAt?: string;
  error?: string;
  durationMs?: number;
  /** Which analyzers were requested for this audit. */
  modules?: AuditModuleSelection;
  screenshots: AuditScreenshots;
  consoleErrors: ConsoleError[];
  failedRequests: FailedRequest[];
  issues: AuditIssue[];
  metrics: AuditMetric[];
  scores: AuditScores;
  summary: string;
  /**
   * Set when the record had to be shed to fit the store's item limit. Not
   * rendered — it exists so a surprising report can be explained.
   */
  truncated?: true;
  /** AI-generated remediation report, added in the AI phase. */
  ai?: AuditAiReport;
};

/**
 * Output of the AI remediation layer. Added in a later phase; optional so
 * reports remain valid when AI is disabled or unavailable.
 */
export type AuditAiReport = {
  /** Whether this came from the live AI provider or the deterministic fallback. */
  source: "ai" | "fallback";
  model?: string;
  executiveSummary: string;
  topIssues: string[];
  recommendations: string[];
  uxSuggestions?: string[];
  generatedAt: string;
};
